apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: "POST"
      queryTimeout: "60s"
    secureJsonData: {}
    version: 1
  - name: TestData
    uid: testdata
    type: grafana-testdata-datasource
    access: proxy
    isDefault: false
    editable: false
